### PR TITLE
Added dataflows within GEH

### PR DESCRIPTION
**Pull request by erduna**
## Description
This adds a model showing what data is needed in various domains, and what data each domain publishes.

This does not indicate which events publish what data, and will be described separately in an .md accompanying this picture once it has been defined.

### CODE REVIEW

**Review by cmgrd — COMMENTED** [review]
I thought we should use the model from ENTSO-E? I.e. no mRID's...

**Comment by erduna** [comment]
> I thought we should use the model from ENTSO-E? I.e. no mRID's...

@MartinFHansen Was this an option for us in the integration events (ie. illustrated here), or just internally in the domains?

**Review by BjarkeMeier — COMMENTED** [review]
I think this can be useful for us developers without deep business knowledge 👍 

I'm a bit unsure about the publishing. What does it mean that aggregations domain publishes metering point ID (which btw. market points domain needs - but surely not from the aggregations domain)?

Also perhaps _needs_ could be grouped by where the individual data comes from.

**Comment by erduna** [comment]
> I think this can be useful for developers without deep business knowledge 👍
> 
> I'm a bit unsure about the publishing. What does it mean that aggregations domain publishes metering point ID (which btw. market points domain needs - but surely not from the aggregations domain)?
> 
> Also perhaps _needs_ could be grouped by which domain the individual data comes from.

Yes, good idea with the grouping, easier than having to look for which domain publishes it. "Publishing" basically means it is data which is output as events from that specific domain. I have not enumerated which events publish what, as I believe this can be done as a team activity in a design session. Alternatively I can make supporting documentation encompassing all events per domain, but that's gonna take some time :)

**Comment by BjarkeMeier** [comment]
> "Publishing" basically means it is data which is output as events from that specific domain. I have not enumerated which events publish what, as I believe this can be done as a team activity in a design session. Alternatively I can make supporting documentation encompassing all events per domain, but that's gonna take some time :)

I'm not sure it' worth creating supporting documentation. Regarding published data I would limit to the data owned by the domain. E.g. aggregations publishing metering point IDs is probably more confusing than helping. I know that in reality a lot more data might be actually published in the events eventually. But that will primarily be for convenience or e.g. identifiers to identify to which entities the published data belongs.

**Comment by erduna** [comment]
> > "Publishing" basically means it is data which is output as events from that specific domain. I have not enumerated which events publish what, as I believe this can be done as a team activity in a design session. Alternatively I can make supporting documentation encompassing all events per domain, but that's gonna take some time :)
> 
> I'm not sure it' worth creating supporting documentation. Regarding published data I would limit to the data owned by the domain. E.g. aggregations publishing metering point IDs is probably more confusing than helping. I know that in reality a lot more data might be actually published in the events eventually. But that will primarily be for convenience or e.g. identifiers to identify to which entities the published data belongs.

It needs to publish MP ID so that timeseries knows which MP the data pertains to. Otherwise it's just random data which you can't place

**Comment by BjarkeMeier** [comment]
> It is limited to data owned by the domain. It needs to publish MP ID so that timeseries knows which MP the data pertains to. Otherwise it's just random data which you can't place

Exactly. So there is a clear distinction between published owned data on published "necessary" identifiers (or other supporting data). It would be nice if that could be made clear in the diagram :-)

**Comment by Sondergaard** [comment]
Why is this diagram needed? 
What gap is it supposed to fill? 
Could it be done another way?

In my opinion it would make more sense that each sub-domain documented what data/events they could provide. This should be done in a consistent way across all sub-domains.

Second - each team needs to known what the other domains can offer. It is OK that a team does not know everything, but then it needs to reach out to the other teams and ask for guidance / assistance. Through this dialog the contracts should be defined and the dependencies documented.

Another concern is - who is responsible for keeping this document updated after this pull request?

**Comment by erduna** [comment]
> 
> 
> Why is this diagram needed?
> What gap is it supposed to fill?
> Could it be done another way?
> 
> In my opinion it would make more sense that each sub-domain documented what data/events they could provide. This should be done in a consistent way across all sub-domains.
> 
> Second - each team needs to known what the other domains can offer. It is OK that a team does not know everything, but then it needs to reach out to the other teams and ask for guidance / assistance. Through this dialog the contracts should be defined and the dependencies documented.
> 
> Another concern is - who is responsible for keeping this document updated after this pull request?

Currently there is confusion in regards to what data is offered from where, and which domain needs what data. This is to alleviate that issue, and is only appropriate to be in the core repo. Completely agree that each subdomain should document what data they can provide, and we should go in this direction as we start defining the contracts between domains. It is important that each contract/event is well documented once defined (and updated when changed).

This also offers a quick overview for "outsiders". As it is open source, it is all our responsibility to update any and all diagrams when we spot inconsistencies.

**Comment by Sondergaard** [comment]
> Currently there is confusion in regards to what data is offered from where, and which domain needs what data. This is to alleviate that issue, and is only appropriate to be in the core repo. Completely agree that each subdomain should document what data they can provide, and we should go in this direction as we start defining the contracts between domains. It is important that each contract/event is well documented once defined (and updated when changed).

If there is confusion as to how the domains interact then I don't think that adding another diagram is the right way to go. I firmly believe that this information should be provided through clear communication. The end goal is that every one knows the concepts of the architecture that has been chosen.

> Besides above we already have simple diagrams documenting the context streams. This is an elaboration on that meant to replace the initial diagrams, which didn't actually document what data flowed between the domains, only the directions.

If we already have started documenting the context streams, why not extend those with the details in this diagram?

**Comment by Sondergaard** [comment]
> > > Currently there is confusion in regards to what data is offered from where, and which domain needs what data. This is to alleviate that issue, and is only appropriate to be in the core repo. Completely agree that each subdomain should document what data they can provide, and we should go in this direction as we start defining the contracts between domains. It is important that each contract/event is well documented once defined (and updated when changed).
> > 
> > 
> > If there is confusion as to how the domains interact then I don't think that adding another diagram is the right way to go. I firmly believe that this information should be provided through clear communication. The end goal is that every one knows the concepts of the architecture that has been chosen.
> > > Besides above we already have simple diagrams documenting the context streams. This is an elaboration on that meant to replace the initial diagrams, which didn't actually document what data flowed between the domains, only the directions.
> > 
> > 
> > If we already have started documenting the context streams, why not extend those with the details in this diagram?
> 
> I believe this contributes to clear communication. The existing diagrams need to be completely reworked. This is that rework.
> 
> If this is not something that is beneficial to the project we can remove it, it's just my suggestion to solving one of the deeper issues we have :)

As I see it the issue is not that information is not available - it is that people/teams are not aware of it. 
- We need to ensure that the teams known where to look.
- Align on the understanding of the architecture.
- Have an understanding of who can help them, and who to reach out to, when they need certain data.

It is more a culture change we need in my opinion.

**Pull request merged**
